import type { StructuredAssistantResponse } from "@ed-support-ai-plug/shared-types";

import type { GenerateResponseInput, ModelAdapter } from "./index.js";

interface OllamaAdapterOptions {
  baseUrl: string;
  model: string;
}

interface OllamaChatResponse {
  message?: {
    content?: string;
  };
}

export class OllamaModelAdapter implements ModelAdapter {
  public readonly provider = "ollama";
  private readonly baseUrl: string;
  private readonly model: string;

  public constructor(options: OllamaAdapterOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.model = options.model;
  }

  public async health() {
    try {
      const response = await fetch(`${this.baseUrl}/tags`);

      if (!response.ok) {
        return {
          status: "degraded" as const,
          provider: this.provider,
          details: `Ollama health check failed with status ${response.status}.`,
        };
      }

      return {
        status: "ok" as const,
        provider: this.provider,
        details: `Ollama is reachable at ${this.baseUrl}.`,
      };
    } catch (error) {
      return {
        status: "down" as const,
        provider: this.provider,
        details: error instanceof Error ? error.message : "Unknown Ollama error.",
      };
    }
  }

  public async generateResponse(input: GenerateResponseInput): Promise<StructuredAssistantResponse> {
    const response = await fetch(`${this.baseUrl}/chat`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: this.model,
        stream: false,
        messages: [
          {
            role: "system",
            content: input.systemPrompt,
          },
          {
            role: "user",
            content: input.userPrompt,
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Ollama chat request failed with status ${response.status}.`);
    }

    const json = (await response.json()) as OllamaChatResponse;
    const content = json.message?.content?.trim();

    if (!content) {
      throw new Error("Ollama returned an empty response.");
    }

    return {
      studentReply: content,
      teacherRationale: "Generated by the Ollama adapter. Structured parsing is still minimal in the scaffold.",
      usedSourceIds: [],
      needsHumanReview: false,
      policyFlags: [],
    };
  }
}
